# Generated by Django 4.2 on 2025-07-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'ToDo'), ('working', 'Working'), ('done', 'Done')], default=False, max_length=16),
        ),
    ]
